using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DeliveryPoint : MonoBehaviour
{
    public int currentBeans = 0;
    public int beansToEat = 50;

    private List<GameObject> beansInSpoon = new List<GameObject>();

    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Bean"))
        {
            Bean bean = other.GetComponent<Bean>();
            if (bean != null && !bean.hasDelivered)
            {
                bean.hasDelivered = true;

                currentBeans++;
                LevelManager.Instance.AddScore(1);
                beansInSpoon.Add(other.gameObject);

                Debug.Log($"ğŸš ì½© ì¶”ê°€ë¨ ({currentBeans}/{beansToEat})");

                if (currentBeans >= beansToEat)
                {
                    StartCoroutine(EatBeansRoutine());
                }
            }
        }
    }


    private IEnumerator EatBeansRoutine()
    {
        Debug.Log("ğŸ¥„ê±°ì¸ì´ í•œ ìŠ¤í‘¼ ë¨¹ìŠµë‹ˆë‹¤!");

        yield return new WaitForSeconds(0.5f); // ì—°ì¶œ íƒ€ì´ë°ìš©

        foreach (var bean in beansInSpoon)
        {
            // ì´í™íŠ¸ë‚˜ ì¶•ì†Œ ì• ë‹ˆë©”ì´ì…˜ ì¤„ ìˆ˜ ìˆìŒ
            BeanPoolManager.Instance.ReturnBean(bean);
        }

        beansInSpoon.Clear();
        currentBeans = 0;

       // LevelManager.Instance.LevelUp();
    }
}
